[build.rarcrack]
base_path = ''
cflags = [ '/EHsc', '/std:c++20', '/utf-8' ]
include = [ 'include' ]
sources = [ 'src\main.cpp' ]

[library.cracklib]
base_path = ''
cflags = [ '-DDEBUG', '-g', '/EHsc', '/W4', '/std:c++20', '/utf-8' ]
include = [ 'include' ]
sources = [ 'src\cracklib.cpp' ]